# Generated by Django 4.1.4 on 2023-08-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='postMarketChangePercent',
            new_name='preMarketChangePercent',
        ),
    ]
