# Generated by Django 4.1.4 on 2023-08-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_postmarketchangepercent_stock_premarketchangepercent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='postMarketChangePercent',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=255, null=True),
        ),
    ]
