# Generated by Django 4.1.4 on 2023-09-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryID', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('numOfStocks', models.IntegerField(max_length=5)),
            ],
        ),
    ]
