# Generated by Django 4.1.4 on 2023-09-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='numOfStocks',
            field=models.IntegerField(),
        ),
    ]
