# Generated by Django 4.1.4 on 2023-09-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_numofstocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='categoryName',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='numOfStocks',
            new_name='totalStocks',
        ),
    ]
